export const FOCUS = 'Focus'
export const BLUR = 'Blur'
export const GETITEM='getItem'
export const MOUSEIN = 'MouseIn'
export const MOUSELEAVE = 'MouseLeave'
export const CHANGEITEM = 'changeItems'
export const CLICKOUTSIDE = 'clickOutside'